-- Boats
DROP TABLE IF EXISTS Boats0;
DROP TABLE IF EXISTS Boats1;

CREATE TABLE Boats1 (
	Z INTEGER PRIMARY KEY,
	T VARCHAR(50) NOT NULL
);

CREATE TABLE Boats0 (
	BL VARCHAR(2),
	BNo INTEGER,
	Z INTEGER NOT NULL,	
	BN VARCHAR(50) NOT NULL,
	SSN CHAR(10) NOT NULL,
	PRIMARY KEY (BL, BNo),
	FOREIGN KEY (Z) REFERENCES Boats1(Z)
);

INSERT INTO Boats1
SELECT DISTINCT Z, T
FROM Boats;
INSERT INTO Boats0
SELECT DISTINCT BL, BNo, Z, BN, SSN
FROM Boats;

-- Coffees
DROP TABLE IF EXISTS Coffees0;
DROP TABLE IF EXISTS Coffees1;
DROP TABLE IF EXISTS Coffees2;

CREATE TABLE Coffees1 (
	DID INTEGER PRIMARY KEY,
	DN VARCHAR(50) NOT NULL,
	DS VARCHAR(50) NOT NULL
);

CREATE TABLE Coffees2 (
	CID INTEGER PRIMARY KEY,
	CN VARCHAR(50) NOT NULL,
	CM VARCHAR(50) NOT NULL
);

CREATE TABLE Coffees0 (
	DID INTEGER,
	HID INTEGER,
	CID INTEGER,
	PRIMARY KEY (DID, HID, CID),
	FOREIGN KEY (DID) REFERENCES Coffees1(DID),
	FOREIGN KEY (CID) REFERENCES Coffees2(CID)
);

INSERT INTO Coffees1
SELECT DISTINCT DID, DN, DS
FROM Coffees;
INSERT INTO Coffees2
SELECT DISTINCT CID, CN, CM
FROM Coffees;
INSERT INTO Coffees0
SELECT DISTINCT DID, HID, CID
FROM Coffees;

-- Customers
DROP TABLE IF EXISTS Customers0;
DROP TABLE IF EXISTS Customers1;

CREATE TABLE Customers1 (
	CZ INTEGER PRIMARY KEY,
	CC VARCHAR(50) NOT NULL
);

CREATE TABLE Customers0 (
	CID INTEGER PRIMARY KEY,
	CN VARCHAR(50) NOT NULL,
	CS VARCHAR(50) NOT NULL,
	CNr INTEGER NOT NULL,
	CZ INTEGER NOT NULL,
	EID INTEGER NOT NULL,
	FOREIGN KEY (CZ) REFERENCES Customers1(CZ)
);

INSERT INTO Customers1
SELECT DISTINCT CZ,CC
FROM Customers;
INSERT INTO Customers0
SELECT DISTINCT CID, CN, CS, CNr, CZ, EID
FROM Customers;

-- Rentals
DROP TABLE IF EXISTS Rentals0;
DROP TABLE IF EXISTS Rentals1;
DROP TABLE IF EXISTS Rentals2;
DROP TABLE IF EXISTS Rentals3;

CREATE TABLE Rentals1 (
	PID INTEGER PRIMARY KEY,
	PN VARCHAR(50) NOT NULL
);

CREATE TABLE Rentals3 (
	HZ INTEGER PRIMARY KEY,
	HC VARCHAR(50) NOT NULL
);

CREATE TABLE Rentals2 (
	HID INTEGER PRIMARY KEY,
	HS VARCHAR(50) NOT NULL,
	HZ INTEGER NOT NULL,
	FOREIGN KEY (HZ) REFERENCES Rentals3(HZ)
);

CREATE TABLE Rentals0 (
	PID INTEGER,
	HID INTEGER,
	S INTEGER NOT NULL,
	PRIMARY KEY (PID, HID),
	FOREIGN KEY (PID) REFERENCES Rentals1(PID),
	FOREIGN KEY (HID) REFERENCES Rentals2(HID)
);

INSERT INTO Rentals1
SELECT DISTINCT PID, PN
FROM Rentals;

INSERT INTO Rentals3
SELECT DISTINCT HZ, HC
FROM Rentals;

INSERT INTO Rentals2
SELECT DISTINCT HID, HS, HZ
FROM Rentals;

INSERT INTO Rentals0
SELECT DISTINCT PID, HID, S
FROM Rentals;
